# Site settings
title: Pawels Jekyll Demo
email: pawelrc@gmail.com
description: > 
  Pawel trying to learn Jekyll
baseurl: "/JekyllDemo" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PawelJanowski7
github_username:  pjanowski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
